import Head from 'next/head'
import Image from 'next/image'
import Logo from '../../components/Logo'


export default function Home() {
  return (
    <>
      <Head>
        <title>Addison.Codes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black w-full h-screen'>
        <div className="container mx-auto">
          <div className="w-96 h-96 mx-auto pt-12">
            <Logo className='mx-auto fill-primary' />
          </div>
          <h1 className='text-center text-9xl text-white font-display uppercase tracking-wide'>Addison<span className='text-primary'>.</span>Codes</h1>
          <div className="flex mt-20 justify-evenly">
          <div className="flex flex-wrap justify-center">
  <div className="rounded-full border-4 border-accent -rotate-6">
    <Image width={320} height={320} src="/hoodiePic.jpg" alt="Addison in a hoodie" className="shadow rounded-full max-w-full h-auto align-middle border-none" />
  </div>
</div>
<div>
  <h2 className="text-5xl text-white text-center">Hi! <span className="italic">I&apos;m <span className="text-accent underline">Addison</span></span>.</h2>
  <h3 className="text-4xl pt-12 text-white text-center">I write <span className="text-secondary">code</span>.</h3>
  <h3 className="text-3xl pt-32 text-white text-center">And do other things...</h3>
</div>
          </div>
        </div>
      </main>
    </>
  )
}
